#############################################
# DO NOT ALTER THE VERSION OR YOUR CONFIG   #
# WILL BE ERASED UPON SERVER RESTART        #
#############################################
config_version:
    version: 1.02e
####################################################################
#list of item id's for respective items and their resulting effects#
#  - helm|chest|legs|boots can only only contain armor item id's   #
#  - sword|shovel|pick|axe can contain any item id as they are     #
#    considered when they are in your hand                         #
#  -DO NOT SET water_walk_block to the same id as lava_walk_block  #
####################################################################
item_ids:
    sword: 283
    shovel: 284
    pick: 285
    axe: 286
    helm: 314
    chest: 315
    legs: 316
    boots: 317
    water_walk_block: 20
    lava_walk_block: 49
############################################################
# Enter a value in seconds that you would like the burning #
# effect to last.                                          #
############################################################
tick_durations:
    fireDuration: 4
    riposteDuration: 4
#############################################
# These control the likelihood of a "proc"  #
# occurring on a successful hit/break event #
#############################################
success_chances:
    hit: 100
    fall: 100
    smelt: 100
    riposte: 100
    fire_resist: 100
#############################################
# Togglable options as true or false        #
#############################################
toggle_option:
    axe_as_weapon: true
    anticheats_installed: false

